### ISSUE TITLE
what does 'KG' mean in source field?

### ISSUE THREAD

**Issue by jcyk** [rloganiv/kglm-data#3]
hi, thank you for open-sourcing this code.

I have a question regarding the annotation. 
I see WIKI NEL COREF and KG for annotation source.
what does KG stand for in the annotations?

**Comment by rloganiv** [comment]
Hi @jcyk,

KG stands for knowledge graph. It indicates the link was created from an exact string match to an entity's alias in the local knowledge graph.

**Comment by jcyk** [comment]
hi @rloganiv  thanks for your quick reply.

could you please explain more about the difference between WIKI and KG?
I am kind of confused.

Thanks!

**Comment by rloganiv** [comment]
WIKI means the link comes from directly from the article HTML.
KG means the link comes from a knowledge graph (in our case WikiData).

**Comment by rloganiv** [comment]
I've added a description to all of the fields to the README. More details about how the KG links are produced are included in [our paper](https://github.com/rloganiv/kglm-data/commit/0218ed70ddfc5741264cb086ca0753b682e942bb). The relevant pieces of code are in the `annotate.py` file.
